import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { saveEvent,getEvent,listEvents,type Transaction } from '../src/server/event-store';
import { authorizeUpload,completeUpload,cancelUpload,listMedia,retryMedia } from '../src/server/media-store';
import { claimJob,finishJob,claimExpired } from '../src/server/job-store';
import { heatmapCounts } from '../src/server/heatmap-store';
const father=randomUUID(),mother=randomUUID(),outsider=randomUUID(),h=randomUUID();let db:PGlite;
const tx:Transaction=fn=>db.transaction(t=>fn(t));
const raw=(ids:string[]=[])=>({requestKey:randomUUID(),title:'媒体测试',body:'',feeling:'',occurredOn:'2025-06-01',uploadIds:ids});
async function upload(auth=father){const u=await authorizeUpload(tx,auth,{name:'photo.jpg',size:123});await completeUpload(tx,auth,String(u.id),{sha256:'a'.repeat(64),size:123,kind:'image',mime:'image/jpeg'});return String(u.id);}
beforeAll(async()=>{db=new PGlite();await db.exec('create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);');for(const name of ['20260907171842_m1_private_events.sql','20260908011410_v1_media.sql'])await db.exec(readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));await db.query('insert into auth.users values($1),($2),($3)',[father,mother,outsider]);await db.query('insert into momentnest.households(id,name) values($1,$2)',[h,'隔离家庭']);await db.query('insert into momentnest.subjects(household_id) values($1)',[h]);await db.query("insert into momentnest.members(household_id,auth_user_id,label) values($1,$2,'爸爸'),($1,$3,'妈妈')",[h,father,mother]);});
afterAll(async()=>{await db.close();});
describe('media save and job contracts',()=>{
 it('纯媒体原件验证、绑定、入队与计数同事务，同键重试只一条',async()=>{const id=await upload(),r=raw([id]);const event=await saveEvent(tx,father,r);expect(await saveEvent(tx,father,r)).toBe(event);expect(await getEvent(db,father,event)).toMatchObject({mediaCount:1,imageCount:1,videoCount:0});expect((await listMedia(db,mother,event)).length).toBe(1);expect((await heatmapCounts(db,father)).find(d=>d.date==='2025-06-01')?.count).toBe(1);expect((await db.query('select state from momentnest.upload_sessions where id=$1',[id])).rows[0]).toEqual({state:'bound'});});
 it('不接受未验证、取消、过期、重复或他人上传',async()=>{const u=await authorizeUpload(tx,father,{name:'test.mp4',size:200});await expect(saveEvent(tx,father,raw([String(u.id)]))).rejects.toMatchObject({code:'VALIDATION'});const id=await upload();await expect(saveEvent(tx,mother,raw([id]))).rejects.toMatchObject({code:'VALIDATION'});await expect(saveEvent(tx,father,raw([id,id]))).rejects.toMatchObject({code:'VALIDATION'});await cancelUpload(tx,father,id);await expect(saveEvent(tx,father,raw([id]))).rejects.toMatchObject({code:'VALIDATION'});const expired=await upload();await db.query("update momentnest.upload_sessions set expires_at=clock_timestamp()-interval '1 second' where id=$1",[expired]);await expect(saveEvent(tx,father,raw([expired]))).rejects.toMatchObject({code:'VALIDATION'});});
 it('实际内容/大小必须与授权一致，拒绝超限和空文件',async()=>{await expect(authorizeUpload(tx,father,{name:'x.jpg',size:51*1024*1024})).rejects.toMatchObject({code:'VALIDATION'});await expect(authorizeUpload(tx,father,{name:'x.mp4',size:0})).rejects.toMatchObject({code:'VALIDATION'});const u=await authorizeUpload(tx,father,{name:'x.jpg',size:42});await expect(completeUpload(tx,father,String(u.id),{size:43,kind:'video',mime:'video/mp4',sha256:'a'.repeat(64)})).rejects.toMatchObject({code:'VALIDATION'});});
 it('保存回滚不留下媒体或任务，verified素材可重新提交',async()=>{const u=await upload();const bad:Transaction=fn=>db.transaction(async t=>{await fn(t);throw Error('connection dropped before commit');});await expect(saveEvent(bad,father,raw([u]))).rejects.toThrow();expect((await db.query('select state from momentnest.upload_sessions where id=$1',[u])).rows[0]).toEqual({state:'verified'});expect((await db.query('select id from momentnest.media where upload_session_id=$1',[u])).rows).toHaveLength(0);await saveEvent(tx,father,raw([u]));});
 it('共同编辑只能追加，保留原件；封面必须属于当前事件',async()=>{const event=await saveEvent(tx,father,raw([await upload()]));const media=await listMedia(db,father,event);await saveEvent(tx,mother,{...raw([await upload(mother)]),id:event,expectedVersion:1,coverMediaId:media[0].id});const e=await getEvent(db,father,event);expect(e.mediaCount).toBe(2);expect(e.author).toBe('爸爸');expect(e.editor).toBe('妈妈');expect(e.coverMediaId).toBe(media[0].id);await expect(saveEvent(tx,mother,{...raw(),id:event,expectedVersion:2,coverMediaId:randomUUID()})).rejects.toMatchObject({code:'VALIDATION'});});
 it('未授权成员无法上传/查看；SQL不能伪造附件数量',async()=>{await expect(authorizeUpload(tx,outsider,{name:'x.jpg',size:2})).rejects.toMatchObject({code:'FORBIDDEN'});const event=await saveEvent(tx,father,raw([await upload()]));await expect(listMedia(db,outsider,event)).rejects.toMatchObject({code:'FORBIDDEN'});await expect(db.query('update momentnest.events set media_count=2,version=version+1 where id=$1',[event])).rejects.toThrow('media count mismatch');});
 it('租约失效可重领，旧任务结果不能覆盖新一轮',async()=>{const old=await claimJob(tx);expect(old).not.toBeNull();await db.query("update momentnest.media_jobs set lease_until=clock_timestamp()-interval '1 second' where media_id=$1",[old!.mediaId]);const next=await claimJob(tx);expect(next!.mediaId).toBe(old!.mediaId);expect(next!.token).not.toBe(old!.token);const result={previewKey:'derivatives/test.jpg',playbackKey:null,capturedText:null,capturedZone:null,metadata:{}};expect(await finishJob(tx,old!,result)).toBe(false);expect(await finishJob(tx,next!,result)).toBe(true);});
 it('失败达到上限后可手动重试，原件和事件时间保持不变',async()=>{const j=await claimJob(tx);await finishJob(tx,{...j!,attempts:3},null);const before=await db.query('select created_at,object_key from momentnest.media where id=$1',[j!.mediaId]);await retryMedia(tx,mother,j!.mediaId);expect((await db.query('select state,generation,attempts from momentnest.media_jobs where media_id=$1',[j!.mediaId])).rows[0]).toMatchObject({state:'pending',generation:2,attempts:0});expect((await db.query('select created_at,object_key from momentnest.media where id=$1',[j!.mediaId])).rows).toEqual(before.rows);});
 it('清理占用后拒绝保存，已绑定原件不会被清理',async()=>{const pending=await upload();await db.query("update momentnest.upload_sessions set expires_at=clock_timestamp()-interval '1 second' where id=$1 or state='bound'",[pending]);const claimed=await claimExpired(tx);expect(claimed.some(u=>u.id===pending)).toBe(true);const bound=await db.query<{id:string}>("select id from momentnest.upload_sessions where state='bound'");expect(claimed.some(u=>bound.rows.some(b=>b.id===u.id))).toBe(false);await expect(saveEvent(tx,father,raw([pending]))).rejects.toMatchObject({code:'VALIDATION'});});
 it('范围查询返回全部匹配事件，媒体数不影响热力图数量',async()=>{const page=await listEvents(db,father,undefined,{start:'2025-06-01',end:'2025-06-01'});expect(page.items.length).toBeGreaterThan(1);const days=await heatmapCounts(db,father);const count=await db.query<{n:number}>("select count(*)::int as n from momentnest.events where occurred_on='2025-06-01'");expect(days.find(d=>d.date==='2025-06-01')?.count).toBe(count.rows[0].n);});
 it('worker无事件写入和删除权限，应用无媒体原件覆盖权限',async()=>{const r=await db.query("select has_table_privilege('momentnest_worker','momentnest.events','update') as event_write,has_table_privilege('momentnest_worker','momentnest.media','delete') as del,has_column_privilege('momentnest_app','momentnest.media','object_key','update') as overwrite");expect(r.rows[0]).toEqual({event_write:false,del:false,overwrite:false});});
});
