 'use client';
import { useMemo, useRef, useState, useEffect } from 'react';
import { ageOn,BIRTHDAY } from '@/domain/dates';
import { cellsFor,yearWindow,allWindow,changeGrain,moveWindow,type DayCount,type Grain,type WindowState } from '@/domain/heatmap';
export function Heatmap({today,days,onSelect,initialWindow,onWindowChange,selection}:{today:string;days:DayCount[];onSelect:(start:string,end:string)=>void;initialWindow?:WindowState;selection?:{start:string;end:string}|null;onWindowChange?:(s:WindowState)=>void}){
 const [state,setState]=useState(initialWindow||yearWindow(Number(today.slice(0,4)),today));
 const [localSelected,setSelected]=useState<{start:string;end:string}|null>(null);const viewport=useRef<HTMLDivElement>(null);
 const selected=selection===undefined?localSelected:selection;
 const cells=useMemo(()=>cellsFor(state,days),[state,days]);
 const years=Array.from({length:Number(today.slice(0,4))-2025+1},(_,i)=>2025+i).reverse();
 function update(s:WindowState){setState(s);onWindowChange?.(s);}
 useEffect(()=>{const active=viewport.current?.querySelector<HTMLElement>('[data-focus="true"]');if(active&&viewport.current)viewport.current.scrollLeft=active.offsetLeft-viewport.current.clientWidth/2+active.offsetWidth/2;},[state.start,state.end,state.grain,state.focus]);
 return <section className="heatmap panel" aria-label="回忆热力图"><div className="section-heading"><div><p className="eyebrow">每一个小格，都是一起走过的日子</p><h2>回忆的温度</h2></div><span className="count-badge">{days.reduce((a,d)=>a+d.count,0)} 段回忆</span></div>
 <div className="heat-controls"><label>年份 <select aria-label="选择年份" value={state.focus.slice(0,4)} onChange={e=>update(yearWindow(Number(e.target.value),today))}>{years.map(y=><option key={y}>{y}</option>)}</select></label><button type="button" onClick={()=>{update(yearWindow(Number(today.slice(0,4)),today));setSelected(null);}}>回到今年</button><button type="button" onClick={()=>{update(allWindow(today));setSelected(null);}}>返回全部时间</button></div>
 <details className="heat-options"><summary>更多时间视图</summary><label className="zoom-label">时间颗粒 <input aria-label="时间颗粒：月、周、日" type="range" min="0" max="2" step="1" value={['month','week','day'].indexOf(state.grain)} onChange={e=>update(changeGrain(state,(['month','week','day'] as Grain[])[Number(e.target.value)],today))}/><span>月 · 周 · 日</span></label></details>
 <div className="range-bar"><button aria-label="查看更早时间范围" disabled={moveWindow(state,-1,today)===state} onClick={()=>update(moveWindow(state,-1,today))}>←</button><span>{state.start.replaceAll('-','.')} — {state.end.replaceAll('-','.')}</span><button aria-label="查看更晚时间范围" disabled={moveWindow(state,1,today)===state} onClick={()=>update(moveWindow(state,1,today))}>→</button></div>
 <div className="heat-scroll" ref={viewport}><div className={`heat-grid ${state.grain}`} role="group" aria-label={state.grain==='day'?'每日记录数量':state.grain==='week'?'每周记录数量':'每月记录数量'}>{cells.map(c=>{const unavailable=c.start>today||c.end<BIRTHDAY;return <button key={c.start} type="button" disabled={unavailable} className={`heat-cell level-${Math.min(c.count,3)} ${unavailable?'future':''} ${selected?.start===c.start&&selected?.end===c.end?'selected':''}`} data-focus={c.start<=state.focus&&c.end>=state.focus} aria-label={`${c.start}${c.end!==c.start?' 至 '+c.end:''}，${c.count}条回忆`} aria-pressed={selected?.start===c.start&&selected?.end===c.end} title={`${c.start} ~ ${c.end} · ${c.count}条`} onClick={()=>{setSelected(c);update({...state,focus:c.start<BIRTHDAY?BIRTHDAY:c.start>today?today:c.start});onSelect(c.start,c.end);}}>{state.grain==='month'?<><small>{c.start.slice(0,4)}</small>{Number(c.start.slice(5,7))}月</>:state.grain==='week'?<small>{c.start.slice(5)}</small>:<span className="sr-only">{c.start}</span>}</button>;})}</div></div>
 <div className="heat-legend">{[0,1,2,3].map(n=><span key={n} className="heat-legend-item"><i className={`level-${n}`} aria-hidden="true"/>{n===3?"3 条及以上":`${n} 条`}</span>)}<span className="muted">按记录条数统计 · 可横向滚动</span></div>
 {selected&&<p className="heat-selection">{selected.start}{selected.end!==selected.start?' 至 '+selected.end:''} · {days.filter(day=>day.date>=selected.start&&day.date<=selected.end).reduce((sum,day)=>sum+day.count,0)} 条 {selected.start>=BIRTHDAY&&selected.start<=today&&<span className="age">{ageOn(selected.start)}</span>}</p>}
 </section>;
}
